      - name: Build Official APK
        run: |
          chmod +x android/gradlew
          cd android && ./gradlew assembleRelease

      - name: Upload Official APK
        uses: actions/upload-artifact@v4
        with:
          name: Dr-Ahlam-Clinic-Official
          path: android/app/build/outputs/apk/release/app-release-unsigned.apk


